server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/hackathon-project?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: M_th__s03!
    driver-class-name: com.mysql.cj.jdbc.Driver


hackathon:
  jwt:
    keystore:
      resource: keys/hackathon.jks
      alias: hackathon
      key-pass: 123456
      store-pass: 123456
logging:
  level:
    com.example.authserverhackathon: debug